name: med_hist_repository
description: "Dart package to manage user history"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.5
  #Firebase
  cloud_firestore: ^4.15.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_storage: ^11.1.0
  
  unicons: ^2.1.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_app.png"
  adaptive_icon_background: "#404776"
  adaptive_icon_foreground: "assets/images/logo_app.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true